# Generated by Django 3.0.8 on 2020-07-23 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('no_of_passengers', models.PositiveSmallIntegerField()),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('ticket_authorized', models.BooleanField(default=True)),
                ('reserved_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('passenger_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=128)),
                ('passenger_age', models.PositiveSmallIntegerField()),
                ('passenger_gender', models.CharField(max_length=10)),
                ('passenger_berth_preference', models.CharField(max_length=3)),
                ('passenger_authorized', models.BooleanField(default=True)),
                ('passenger_reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Reservation')),
                ('passenger_ticket_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TicketStatus')),
            ],
        ),
    ]
