# Generated by Django 3.0.8 on 2020-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_passengers_passenger_berth_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='is_alloted',
            field=models.BooleanField(default=False),
        ),
    ]
