# Generated by Django 3.0.8 on 2020-07-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_berth_is_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='ticket_name',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
