# Generated by Django 3.0.8 on 2020-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_berth_ticket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='passenger_ticket_status',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.DeleteModel(
            name='TicketStatus',
        ),
    ]
