# Generated by Django 3.0.8 on 2020-07-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_berth_rac_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='passenger_berth_alloted',
            field=models.UUIDField(default=None),
        ),
    ]
