# Generated by Django 3.0.8 on 2020-07-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200724_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='passenger_reservation_id',
            field=models.UUIDField(default=None),
        ),
    ]
