# Generated by Django 3.0.8 on 2020-07-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200724_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='passenger_reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Reservation'),
        ),
    ]
