# Generated by Django 3.0.8 on 2020-07-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200724_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='passenger_berth_alloted',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
